baseurl: ""

# Name of website
title: 分享编程、产品知识

# Short description of your site
description: 长大后，你用实际行动成了自己喜欢的人了吗?

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
    style: compressed

plugins:
  - jekyll-sitemap
